# Changes here will be overwritten by Copier
_commit: v1.8.3
_src_path: .\copier-phil65\
author_email: philipptemminghoff@googlemail.com
author_fullname: Philipp Temminghoff
author_username: phil65
copyright_date: '2024'
copyright_holder: Philipp Temminghoff
copyright_holder_email: philipptemminghoff@googlemail.com
libraries_use_pydantic: true
libraries_use_qt: false
project_description: A pydantic-ai based Agent with LLMling backend
project_name: LLMling-Agent
python_minimum_version: '3.12'
python_package_command_line_name: llmling-agent
python_package_distribution_name: llmling-agent
python_package_import_name: llmling_agent
repository_name: llmling-agent
repository_namespace: phil65
repository_provider: github.com

